export { default as getStaticProps } from '../utils/initial-props/pagesGetStaticProps'
export { default as getStaticPaths } from '../utils/initial-props/pagesGetStaticPaths'
// export { Auth0Page as default } from '../components/pages/Auth0Page'
export { LmDefaultPage as default } from '../components/pages/DefaultPage'
// export { auth0GetServerSideProps as getServerSideProps } from '../utils/initial-props/auth0PagesGetServerSideProps'
